[workspace]
authors = ["mashriram <mashriram@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "mojotorch"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
